# Generated by Django 5.1.3 on 2024-11-08 17:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogindex',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
